Exception on /auth/login [POST]
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\PycharmProjects\pythonProject\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\py.flask\flaskProject_wenda\blueprints\auth.py", line 38, in login
    app.logger.info(f"用户{user.username}登录成功")
AttributeError: module 'app' has no attribute 'logger'
